M48
; DRILL file {KiCad 9.0.0} date 2025-03-25T20:25:00+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-25T20:25:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X145.2Y-145.45
X145.2Y-152.45
X169.8Y-102.55
X169.8Y-109.55
M30
